# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 372101c3e2af04c9a1a3e7023658c1ba8e0e2bbb668f647c613cd12f5b406917dfb56120c718690232166569a302869250d25cdfafa6c418e663f8fe9f1a580f

test:
  secret_key_base: 02c65b4a18a292b53c3ec45b65be0a6b2b1d1f7b1348d4ee7741d1b81383dc62a6aeb3beb3f59e9e5a2b7592c8a3af41df73f2dd27a6d0f7d6c883ac9633a427

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
